### PR TITLE
Storing `AVAsset` per url to save cached frames and data (avoiding rebuffering)

### PR DESCRIPTION
**Pull request by AndriiMoskvin**
@aol-public/mobile-sdk-team: Ready for review.

[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-262)

### CODE REVIEW

**Comment by oleksii-demedetskyi** [comment]
I can't find a clearing of the cache. How we limit SDK memory consumption in this case?

**Comment by AndriiMoskvin** [comment]
No limit at all.

**Comment by AndriiMoskvin** [comment]
No cache clean.

**Comment by AndriiMoskvin** [comment]
This is a room for improvement.

**Comment by oleksii-demedetskyi** [comment]
Is it safe to ship with unlimited memory growth?

**Comment by AndriiMoskvin** [comment]
We are not shipping it yet - just in Beta.
My plan is to have PR that controlling this today. Stay tuned.

**Pull request merged**
